version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"  # expose only if needed
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: iocl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nlp_worker:
    build:
      context: .
      dockerfile: Dockerfile.nlp  # Your worker Dockerfile
    depends_on:
      - kafka
      - postgres
    environment:
      PG_DSN: postgresql://postgres:postgres@postgres:5432/iocl

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.api  # Your FastAPI Dockerfile
    depends_on:
      - kafka
      - postgres
    ports:
      - "8000:8000"
    environment:
      PG_DSN: postgresql://postgres:postgres@postgres:5432/iocl
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

volumes:
  postgres_data:

