


services:
 
  postgres:

   image: pgvector/pgvector:pg16
   environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    POSTGRES_DB: iocl
   ports:
    - "5432:5432"
   volumes:
    - pgdata:/var/lib/postgresql/data


  nlp_worker:
   build:
    context: .
    dockerfile: Dockerfile.worker

   volumes:
      - .:/app                
   working_dir: /app
   command: ["python", "workers/nlp_worker.py"]
   depends_on:
      - postgres
      
   environment:
      - PG_DSN=postgresql://postgres:postgres@postgres:5432/iocl
      - HF_HOME=/cache        
   restart: unless-stopped
  grafana:
   image: grafana/grafana:10.3.1
   ports:
      - "3000:3000"
   environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
   depends_on:
      - postgres

volumes:
  pgdata:

